"use client";
import { useEffect, useState } from 'react';
import { withBase } from '../../components/NextUiConfig';

type Item = { href: string; title: string; date?: string; tags?: string[] };

export default function AgentsPage() {
  const [items, setItems] = useState<Item[]>([]);
  const [q, setQ] = useState('');
  useEffect(() => {
    (async () => {
      try {
        const res = await fetch(withBase('/logs-index.json'));
        const all: Item[] = await res.json();
        const filtered = all.filter((x) =>
          /multi[- ]agent/i.test(x.title || '') || (x.tags || []).some(t => t.toLowerCase() === 'agents'));
        filtered.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
        setItems(filtered);
      } catch {}
    })();
  }, []);
  const show = items.filter((x) => (x.title || '').toLowerCase().includes(q.toLowerCase()));
  return (
    <div>
      <h2 style={{ marginTop: 0 }}>Agents</h2>
      <p>Recent multi-agent reports generated by the orchestrator.</p>
      <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="filter by title" style={{ padding: '8px', borderRadius: 6, border: '1px solid #cbd5e1' }} />
      <ul style={{ listStyle: 'none', padding: 0 }}>
        {show.map((x) => (
          <li key={x.href} style={{ padding: '8px 0', borderBottom: '1px solid #e2e8f0' }}>
            <a href={x.href + '/'} style={{ color: '#0ea5e9', textDecoration: 'none' }}>{x.title}</a>
            {x.date ? <small style={{ marginLeft: 8, color: '#64748b' }}>{x.date}</small> : null}
            {(x.tags || []).includes('agents') && <span style={{ marginLeft: 8, padding: '2px 6px', borderRadius: 6, background: '#ecfeff', color: '#155e75', fontSize: 12 }}>#agents</span>}
          </li>
        ))}
        {!show.length && <li style={{ color: '#64748b', padding: '12px 0' }}>No agent reports yet.</li>}
      </ul>
    </div>
  );
}
