name: Monthly Agents & Memory

on:
  schedule:
    # Run monthly on the 1st at 02:15 UTC
    - cron: '15 2 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: read

concurrency:
  group: monthly-agents-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-agent-zero-and-memory:
    name: Agent Zero + Memory Build
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'site/package-lock.json'

      - name: Cache node_modules (fallback)
        id: node-cache
        uses: actions/cache@v4
        with:
          path: |
            site/node_modules
          key: node-mod-${{ runner.os }}-${{ hashFiles('site/package-lock.json') }}
          restore-keys: |
            node-mod-${{ runner.os }}-

      - name: Install deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          cd site
          npm ci || npm i

      - name: Prebuild (indexes)
        run: |
          cd site
          node scripts/prebuild.mjs

      - name: GitHub CLI Status Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Using GitHub CLI instead of AI providers"
          gh repo view --json description,topics,url
          gh issue list --limit 5
          gh pr list --limit 5
          echo "GitHub CLI provider selected for simplified operations"
          echo "provider=github" >> $GITHUB_OUTPUT

      - name: Monthly GitHub Summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd site
          echo "Running monthly summary using GitHub CLI"
          echo "Checking repository activity and logs"
          # Simple log counting instead of AI processing
          find logs -name "*.md" -type f | wc -l > /tmp/log_count.txt
          echo "Total logs found: $(cat /tmp/log_count.txt)"
          echo "Monthly summary completed using GitHub CLI"

      - name: Build memory index
        run: |
          node site/scripts/ai-cli.mjs tool memory build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: memory-and-agents
          path: |
            logs/incoming/**
            logs/memory/**
            site/public/memory-index.json

      - name: Auto-commit memory index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add site/public/memory-index.json logs/memory || true
          git commit -m "chore(memory): monthly memory index update" || echo "No changes"
          git push || true
