name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: site/package-lock.json

      - name: Install deps
        run: |
          cd site
          npm ci || npm i

      - name: Prebuild
        run: |
          cd site
          npm run prebuild

      - name: Build & Export
        run: |
          cd site
          npm run build
          npm run export
          tar -czf ../site-export.tar.gz -C out .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-export
          path: site-export.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: site-export.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
